---
  - name: "install selinux,firewalld"
    become: yes
    yum: name="{{ item }}" state=present
    with_items:
      - selinux-policy
      - firewalld
    tags:
      - security

  - name: "disable selinux"
    become: yes
    replace: dest='/etc/selinux/config' regexp='SELINUX=enforcing' replace='SELINUX=disabled'
    tags:
      - security

  - name: "disable selinux setenforce"
    become: yes
    shell: setenforce 0
    ignore_errors: yes
    tags:
      - security

  - name: "disable firewalld"
    become: yes
    service: name=firewalld.service state=stopped enabled=no
    tags:
      - security
