---      
  - name: "install selinux,firewalld"
    become: yes
    yum: name="{{ item }}" state=present
    with_items:
      - selinux-policy
      - firewalld
    when: ansible_distribution_version|int == 7
    tags:
      - security

  - name: "install selinux,firewalld"
    become: yes
    yum: name="{{ item }}" state=present
    with_items:
      - selinux-policy
      - iptables
    when: ansible_distribution_version|int == 6
    tags:
      - security

  - name: "disable selinux"
    become: yes
    replace: dest='/etc/selinux/config' regexp='SELINUX=enforcing' replace='SELINUX=disabled'
    tags:
      - security

  - name: "disable selinux setenforce"
    become: yes
    shell: setenforce 0
    ignore_errors: yes
    tags:
      - security

  - name: "disable firewalld"
    become: yes
    systemd: name=firewalld.service state=stopped enabled=no
    when: ansible_distribution_version|int == 7
    tags:
      - security

  - name: "disable firewalld"
    become: yes
    service: name=iptables state=stopped enabled=no
    when: ansible_distribution_version|int == 6
    ignore_errors: yes
    tags:
      - security