---
  - name: Update the /etc/ssh/sshd_config file usedns
    become: yes
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^UseDNS"
      line: "UseDNS no"
      insertafter: EOF
      state: present
    register: ssh_config

  - name: Update the /etc/ssh/sshd_config file ClientAliveInterval
    become: yes
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^ClientAliveInterval"
      line: "ClientAliveInterval 180"
      insertafter: EOF
      state: present
    register: ssh_config

  - name: Update the /etc/ssh/sshd_config file ClientAliveCountMax
    become: yes
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^ClientAliveCountMax"
      line: "ClientAliveCountMax 30"
      insertafter: EOF
      state: present
    register: ssh_config

  - name: Update the /etc/ssh/sshd_config file addressfamily
    become: yes
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^AddressFamily"
      line: "AddressFamily inet"
      insertafter: EOF
      state: present
    register: ssh_config
  
  - name: Restart ssh
    become: yes
    systemd:
      name: sshd
      state: restarted
