####################################################
#guac_pass: Guac123!
#xrdp_pass: Xrdp123!
####################################################
####################################################
#### docker user specific value  ###################
DOCKERSUBNET: "10.153.0.0/16"
VXLAN_DEV: "eth0"
BRNAME: "raconxx"
DOCKER_VOLUME_PATH: "/rac_on_docker"
MEDIA_PATH: /u01/downloadmedia
MEDIA_COPY: "true"
DB_MEDIA1: linuxx64_12201_database.zip
GRID_MEDIA1: linuxx64_12201_grid_home.zip
####################################################
####common VIRT_TYPE specific value ################
DELETE_CMD_OPS: "-f"
DELETE_CMD: "docker rm {{ DELETE_CMD_OPS }}"
START_CMD: "docker start"
START_CMD_OPS: ""
STOP_CMD: "docker stop"
STOP_CMD_OPS: ""
INSTALL_OPS: "-ignorePrereqFailure"
DHCPCLIENT: ""
####################################################
####docker system  specific value ##################
IMAGE: "s4ragent/rac_on_xx:OEL6"
#CAP_OPS: "--cap-add=NET_ADMIN"
DOCKER_CAPS: "--privileged=true --security-opt seccomp=unconfined -v /boot/:/boot:ro --tmpfs=/run -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /dev:/dev -v /lib/modules:/lib/modules:ro"
#DOCKER_CAPS: "--security-opt seccomp=unconfined --cap-add=SYS_ADMIN --cap-add=SYS_NICE  --cap-add=SYS_RESOURCE --cap-add=NET_ADMIN -v /boot/:/boot:ro --tmpfs=/run -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /dev:/dev"
DOCKER_START_OPS: "--restart=always"
TMPFS_OPS: "--shm-size=1200m"
####################################################
#WindowManager: "xfce"
####ansible specific
ansible_ssh_user: opc
ansible_ssh_private_key_file: raconxx
dns: dnsmasq
#####for NFS option values
##### device size = base_size + multi_size * node count
storage_type: "nbd"
#nbd_local_container: "true"
NFS_OPS:  "rw,bg,hard,nointr,rsize=1048576,wsize=1048576,tcp,vers=4,timeo=600,actimeo=0"
ORA_DATA: /u01/oradata
VOTE_DEV: /u01/oradata/vote.img
VOTE_BASE_SIZE: 40960
VOTE_MULTI_SIZE: 2048
VOTE_DISKGROUP_NAME: VOTE
DATA_DEV: /u01/oradata/data.img
DATA_BASE_SIZE: 5120
DATA_MULTI_SIZE: 1024
DATA_DISKGROUP_NAME: DATA
FRA_DEV: /u01/oradata/fra.img
FRA_BASE_SIZE: 25600
FRA_MULTI_SIZE: 0
FRA_DISKGROUP_NAME: FRA
ASM_STRING: /u01/oradata/*
DNFS: enable
###
NODEPREFIX: node
DOMAIN_NAME: public
SCAN_NAME: scan
INSTALL_LANG: ja
SWAP_SIZE: 4096
CLUSTER_NAME: node-cluster
DBNAME: ORCL
SIDNAME: ORCL
SYSPASSWORD: oracle123
SYSTEMPASSWORD: oracle123
REDOFILESIZE: 100
ASMSYSPASSWORD: oracle123
ASMMONPASSWORD: oracle123
CHARSET: AL32UTF8
NCHAR: AL16UTF16
MEMORYTARGET: 2400
TEMPLATENAME: General_Purpose.dbc
DATABASETYPE: MULTIPURPOSE
dbca: paralell
