---
  - name: "disable fastestmirror"
    become: yes
    shell: sed -i 's/enabled=1/enabled=0/' /etc/yum/pluginconf.d/fastestmirror.conf 
    ignore_errors: true
    tags:
      - centos2oel

  - name: "yum clean all"
    become: yes
    shell: yum -y clean all
    ignore_errors: true
    tags:
      - centos2oel


  - name: "yum clean metadata"
    become: yes
    shell: yum -y clean metadata
    ignore_errors: true
    tags:
      - centos2oel


  - name: "check oracle-release"
    become: yes
    shell: cat /etc/oracle-release
    ignore_errors: true
    register: centos2oel_rerult
    tags:
      - centos2oel

  - name: "centos2oel"
    become: yes
    shell: curl -O https://linux.oracle.com/switch/centos2ol.sh && sh centos2ol.sh
    when: centos2oel_rerult.rc != 0
    tags:
      - centos2oel


  - name: "centos2oel distro-sync"
    become: yes
    shell: yum -y distro-sync
    when: centos2oel_rerult.rc != 0
    tags:
      - centos2oel

  - name: "dummy yum command (GPGKEY INSTALL)"
    become: yes
    shell: yum -y search nfs-utils
    ignore_errors: true
    tags:
      - centos2oel

  - name: "install kernel"
    become: yes
    yum: name="kernel-uek-4*" state=latest enablerepo=ol7_UEKR4 disablerepo=ol7_UEKR3
    when: SWITCH_KERNEL is defined and SWITCH_KERNEL !=""
    tags:
      - centos2oel
      - switchkernel


  - name: "switch kernel"
    become: yes
    shell: "grub2-set-default {{ SWITCH_KERNEL }} && grub2-mkconfig -o /etc/grub2.cfg"
    when: SWITCH_KERNEL is defined and SWITCH_KERNEL !=""
    tags:
      - centos2oel
      - switchkernel

  - name: "edit ifcfg-eth0"
    become: yes
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      regexp: "^MTU"
      line: "MTU {{ MTU }}"
      insertafter: EOF
      state: present
    when: 	MTU is defined
    tags:
      - centos2oel
      - reboot

  - name: reboot
    become: yes
    shell: sleep 2 && reboot &
    when: centos2oel_rerult.rc != 0 or ( SWITCH_KERNEL is defined and SWITCH_KERNEL !="" ) or MTU is defined
    async: 1
    poll: 0
    ignore_errors: true
    tags:
      - centos2oel
      - reboot


  - name: "sleep 180s"
    local_action: shell sleep 180s
    run_once: true
    when: centos2oel_rerult.rc != 0 or ( SWITCH_KERNEL is defined and SWITCH_KERNEL !="" )
    tags:
      - centos2oel
      - reboot


